/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author User
 */
public class FrBantuan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrBantuan
     */
    public FrBantuan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setClosable(true);

        jTabbedPane1.setBackground(new java.awt.Color(51, 102, 255));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(610, 555));

        jLayeredPane1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setText("Form jurnal umum\n\n-jika akan mencari data jurnal maka langkah-langkah yang harus dilakukan yaitu:\n1. ketik nama akun yang akan dicari pada kolom pencarian\n2. data yang dicari akan muncul.\n\njika akan merefresh data jurnal maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol refresh\n2. maka akan tampil keseluruhan data jurnal.");
        jScrollPane8.setViewportView(jTextArea8);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("JURNAL UMUM", jLayeredPane1);

        jLayeredPane2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Form Kas Keluar\n-jika akan menambah kas keluar maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol tambah\n2. pada kotak isian no_transaksi, pilih id akun, input tanggal, keterangan, dan\nnominal.\n3. kemudian klik simpan, maka akan tersimpan.\n\n-jika akan mencari data kas keluar maka langkah-langkah yang harus dilakukan yaitu:\n1. ketik nama akun yang akan dicari pada kolom pencarian\n2. data yang dicari akan muncul.\n\njika akan merefresh data kas keluar maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol refresh\n2. maka akan tampil keseluruhan data kas keluar.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("KAS KELUAR", jLayeredPane2);

        jLayeredPane3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jTextArea9.setText("Form Kas masuk\n-jika akan menambah kas masuk maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol tambah\n2. pada kotak isian no_transaksi, pilih id akun, input tanggal, keterangan, dan\nnominal.\n3. kemudian klik simpan, maka akan tersimpan.\n\n-jika akan mencari data kas masuk maka langkah-langkah yang harus dilakukan yaitu:\n1. ketik nama akun yang akan dicari pada kolom pencarian\n2. data yang dicari akan muncul.\n\njika akan merefresh data kas masuk maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol refresh\n2. maka akan tampil keseluruhan data kas masuk.");
        jScrollPane9.setViewportView(jTextArea9);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane3.setLayer(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("KAS MASUK", jLayeredPane3);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Form Laporan\n-jika akan menampilkan laporan maka langkah-langkah yang harus dilakukan yaitu:\n1. input periode tanggal\n2. klik laporan yang di inginkan, maka akan ttampil laporan.\n");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane4.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("LAPORAN", jLayeredPane4);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("1. membackup dan restore database.\n2. bantuan\n3. tombol keluar dari sistem");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane5.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("PENGATURAN", jLayeredPane5);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Form Karyawan\n-jika akan menambah kas keluar maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol tambah\n2. pada kotak isian no_transaksi, pilih id akun, input tanggal, keterangan, dan\nnominal.\n3. kemudian klik simpan, maka akan tersimpan.\n\n-jika akan mencari data kas keluar maka langkah-langkah yang harus dilakukan yaitu:\n1. ketik nama akun yang akan dicari pada kolom pencarian\n2. data yang dicari akan muncul.\n\njika akan merefresh data kas keluar maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol refresh\n2. maka akan tampil keseluruhan data kas keluar.");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        jLayeredPane6.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Karyawan", jLayeredPane6);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("1. instal xampp dan netbeans 7.4\n2. aktifkan xampp dan klik phpmyadmin untuk membuka database db_akuntansi.\n3. buka netbeans 7.4 , klik open project, pilih akuntansi.\n4. kemudian running program akuntansi arus kas");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane7.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("PETUNJUK INSTALASI", jLayeredPane7);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("Form akun\n-jika akan menambah akun maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol tambah\n2. lengkapi form.\n3. kemudian klik simpan, maka akan tersimpan.\n\n-jika akan mencari data akun maka langkah-langkah yang harus dilakukan yaitu:\n1. ketik nama akun yang akan dicari pada kolom pencarian\n2. data yang dicari akan muncul.\n\njika akan merefresh data akun maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol refresh\n2. maka akan tampil keseluruhan data akun.");
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane8.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("PERKIRAAN", jLayeredPane8);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("Form Barang\n\n-jika akan menambah barang maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol tambah\n2. isi form barang\n3. kemudian klik simpan, maka akan tersimpan.\n\n-jika akan mengubah barang maka langkah-langkah yang harus dilakukan yaitu:\n1. klik data yang akan diubah\n2. isi form barang\n3. kemudian klik ubah, maka data akan terubah.\n\n-jika akan mencari data barang maka langkah-langkah yang harus dilakukan yaitu:\n1. ketik nama barang yang akan dicari pada kolom pencarian\n2. data yang dicari akan muncul.\n\njika akan merefresh data barang maka langkah-langkah yang harus dilakukan yaitu:\n1. klik tombol refresh\n2. maka akan tampil keseluruhan data barang.");
        jScrollPane7.setViewportView(jTextArea7);

        javax.swing.GroupLayout jLayeredPane9Layout = new javax.swing.GroupLayout(jLayeredPane9);
        jLayeredPane9.setLayout(jLayeredPane9Layout);
        jLayeredPane9Layout.setHorizontalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane9Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane9Layout.setVerticalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        jLayeredPane9.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("BARANG", jLayeredPane9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
